[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
agent-db = { path = "../agent-db" }
home = { path = "../agent-home" }
async-trait = { workspace = true }
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
