[package]
name = "network-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../agent-types" }
anyhow = { workspace = true }
globset = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "rt", "sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "rt"] }
