pub mod browser;
mod builtin_pet;
pub mod desktop_pet;
pub mod desktop_preferences;
pub mod icon;
pub mod onboarding;
pub mod pet_generation;
pub mod pet_scene;
pub mod ui_style;
pub mod updater;
pub mod wallpaper;
pub mod workspace_check;
