pub mod browser;
pub mod desktop_ambience;
mod builtin_pet;
pub mod desktop_pet;
mod pet_placement;
mod pet_platform;
pub mod desktop_preferences;
pub mod icon;
pub mod interface_tour;
pub mod onboarding;
pub mod pet_generation;
pub mod pet_scene;
pub mod ui_style;
pub mod updater;
pub mod wallpaper;
pub mod workspace_check;
