pub mod browser;
mod builtin_pet;
mod builtin_pet_apng;
mod pet_apng;
pub mod desktop_ambience;
pub mod desktop_pet;
pub mod desktop_preferences;
pub mod icon;
pub mod interface_tour;
pub mod onboarding;
pub mod pet_generation;
mod pet_placement;
pub mod pet_roaming;
mod pet_roaming_plan;
mod pet_platform;
pub mod pet_scene;
mod pet_task_motion;
pub mod pet_tasks;
pub mod ui_style;
pub mod updater;
pub mod wallpaper;
pub mod workspace_check;
