export const COPY = {
  zh: {
    skipIntro: "跳过动画",
    cancelTest: "取消等待",
    testCost: "测试会向当前服务发送一次很短的生成请求，可能产生少量费用。",
    loadingProviders: "正在读取模型服务…连接验证通过后才能继续。",
    progressFailed: "进度未保存，请重试；你可以继续填写。",
    finishFailed: "初始化未能全部保存，请检查连接后重试。已有设置会保留。",
    demoLabel: "交互演示 · 模型结果为模拟，不发送真实请求",
    demoConnected: "演示连接成功（模拟结果）",
    savedTitle: "演示摘要",
    savedSub: "这是模拟界面。正式初始化必须接通模型后，才能进入 App。",
    sandboxUnavailable: "沙箱状态未确认，请在设置中检查",
    modelStatuses: {
      verified: "本次连接测试已通过",
      unavailable: "尚未配置可用模型",
      demo: "演示数据 · 未实际连接",
    },
    hello: "你好，我是 Astro",
    introSub: "你的本地 AI 工作站，正在苏醒。",
    personalizeEyebrow: "01 · 个性化",
    personalizeTitle: "先让这里更像你的工作空间",
    personalizeSub: "语言和外观会立即生效，之后也可以随时在设置中修改。",
    language: "界面语言",
    theme: "外观主题",
    agentName: "Agent 名称（可选）",
    agentNamePlaceholder: "Astro",
    chinese: "中文",
    english: "English",
    light: "浅色",
    dark: "深色",
    auto: "跟随系统",
    providerEyebrow: "02 · 连接模型",
    providerTitle: "为 Astro 接入思考能力",
    providerSub:
      "必须完成一次真实模型连接测试后才能继续。密钥使用系统安全存储，不写入初始化草稿。",
    provider: "模型服务",
    apiKey: "API Key",
    apiKeyStored: "密钥已保存，可获取模型列表",
    apiKeyPlaceholder: "输入 API Key",
    model: "默认模型",
    loadModels: "保存密钥并获取模型",
    loadingModels: "正在获取模型…",
    chooseModel: "请选择默认模型",
    searchModels: "搜索模型名称或 ID",
    noMatchingModels: "没有匹配的模型，试试其他关键词",
    modelLoadHint: "先获取模型列表，再选择默认模型。此步骤不发起聊天生成请求。",
    endpoint: "服务地址（base_url）",
    test: "保存并测试连接",
    testing: "正在验证连接",
    testSuccess: "连接成功",
    noProviders: "没有可用的 Responses API 模型服务。请检查安装配置。",
    workspaceEyebrow: "03 · 工作空间与安全",
    workspaceTitle: "决定 Astro 从哪里开始工作",
    workspaceSub:
      "可以关联一个代码或资料目录；未选择时会使用 Astro 默认工作空间。",
    chooseFolder: "选择工作目录",
    changeFolder: "更换目录",
    defaultWorkspace: "使用默认工作空间",
    permission: "执行权限",
    ask: "执行前询问",
    askSub: "推荐。涉及写入或高风险操作时先征得你的同意。",
    approve: "自动处理常规操作",
    approveSub: "减少打断，高风险操作仍由安全策略约束。",
    networkNote: "网络默认可用；本机、私网和云元数据地址仍受 SSRF 防护。",
    back: "返回",
    continue: "继续",
    finish: "完成设置",
    finishing: "正在完成初始化",
    completeTitle: "一切准备就绪",
    completeSub: "初始化检查已通过。选一个任务开始，或直接进入 Astro。",
    healthAgent: "Agent 身份",
    healthModel: "模型连接",
    healthWorkspace: "工作空间",
    healthPermission: "执行权限",
    enter: "空白开始",
    retry: "重试",
  },
  en: {
    skipIntro: "Skip animation",
    cancelTest: "Cancel waiting",
    testCost:
      "This test sends a short generation request to the provider and may incur a small charge.",
    loadingProviders: "Loading providers… A verified connection is required.",
    progressFailed: "Progress was not saved. Retry; you can keep editing.",
    finishFailed:
      "Some setup changes could not be saved. Check connectivity and retry. Saved settings are kept.",
    demoLabel: "Interactive demo · simulated model results, no real requests",
    demoConnected: "Demo connected (simulated result)",
    savedTitle: "Demo summary",
    savedSub:
      "This is a demo. Production setup requires a verified model before entering the app.",
    sandboxUnavailable: "Sandbox status unconfirmed; check Settings",
    modelStatuses: {
      verified: "Connection verified this run",
      unavailable: "No usable model configured",
      demo: "Demo data · not connected",
    },
    hello: "Hello, I'm Astro",
    introSub: "Your local AI workstation is waking up.",
    personalizeEyebrow: "01 · Personalize",
    personalizeTitle: "Make this workspace feel like yours",
    personalizeSub:
      "Language and appearance update instantly and remain editable in Settings.",
    language: "Interface language",
    theme: "Appearance",
    agentName: "Agent name (optional)",
    agentNamePlaceholder: "Astro",
    chinese: "中文",
    english: "English",
    light: "Light",
    dark: "Dark",
    auto: "System",
    providerEyebrow: "02 · Connect a model",
    providerTitle: "Give Astro its reasoning engine",
    providerSub:
      "A successful model connection test is required. Keys use secure system storage and never enter setup drafts.",
    provider: "Model provider",
    apiKey: "API Key",
    apiKeyStored: "Key saved. Load models to continue.",
    apiKeyPlaceholder: "Enter API Key",
    model: "Default model",
    loadModels: "Save key and load models",
    loadingModels: "Loading models…",
    chooseModel: "Choose a default model",
    searchModels: "Search model name or ID",
    noMatchingModels: "No matching models. Try another keyword.",
    modelLoadHint:
      "Load the provider's model list, then choose a default. This step does not generate a chat response.",
    endpoint: "Service address (base_url)",
    test: "Save and test connection",
    testing: "Verifying connection",
    testSuccess: "Connection successful",
    noProviders:
      "No Responses API provider is available. Check the installation configuration.",
    workspaceEyebrow: "03 · Workspace & safety",
    workspaceTitle: "Choose where Astro starts working",
    workspaceSub:
      "Attach a code or document folder, or continue with Astro's default workspace.",
    chooseFolder: "Choose workspace",
    changeFolder: "Change folder",
    defaultWorkspace: "Use default workspace",
    permission: "Execution permissions",
    ask: "Ask before acting",
    askSub: "Recommended. Astro asks before writes or higher-risk actions.",
    approve: "Handle routine actions",
    approveSub:
      "Fewer interruptions; higher-risk actions remain policy controlled.",
    networkNote:
      "Network access is available by default; local, private, and cloud metadata targets remain SSRF-protected.",
    back: "Back",
    continue: "Continue",
    finish: "Finish setup",
    finishing: "Finishing setup",
    completeTitle: "Everything is ready",
    completeSub:
      "Initialization checks passed. Pick a first task or enter Astro with a blank composer.",
    healthAgent: "Agent identity",
    healthModel: "Model connection",
    healthWorkspace: "Workspace",
    healthPermission: "Execution permissions",
    enter: "Start blank",
    retry: "Retry",
  },
} as const;
